name: build
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Rust ${{ matrix.target }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          [
            x86_64-unknown-linux-musl,
            x86_64-apple-darwin,
            x86_64-pc-windows-msvc,
            x86_64-unknown-linux-gnu,
          ]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=${{ matrix.target }}
          use-cross: true
      - name: Zip output
        run: zip ${{ matrix.target }}.zip ${{ matrix.target }}/release/
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: pasona.zip
